Feature/3 transfer
PROG17/KallesALMBank pull request #5
Opened 2018-11-13 22:30 UTC by Charbely

Pull request för feature/3 transfer.

-Ägaren av projektet ska testköra koden på sin egen dator och granska den.

-Ägaren av projektet ska sedan ge återkoppling om något behöver förbättras eller om allt är okej i kommentarer på pull requesten i Github.

-Använd fliken Commits respektive Files changed för att granska vad som ändrats i pull requesten.

-När kodgranskningen är klar ska ägaren av projektet använd knappen merge på pull requesten för att gör en merge av din kod i feature-branchen till develop-branchen.

2018-11-14 05:52 UTC, applejag requested changes
Ser bra ut Charbel! Men du behöver korrigera lite först.

2018-11-14 05:52 UTC, jilleJr commented on KallesBank/Controllers/BankController.cs
> +                ModelState.AddModelError(nameof(model.AccountId1), error);
Error från account2 läggs till på account1.

2018-11-14 05:52 UTC, jilleJr commented on BankRepo/BaseBankRepository.cs
> +                throw new ArgumentException("Amount must be positive!", nameof(amount));
Finns inget test som testar utföra <=0 scenariot

2018-11-14 05:52 UTC, jilleJr commented on BankRepo/IBankRepository.cs
> +        [CanBeNull]
En void metod kan inte returnera värde, så CanBeNull är felaktigt utlagd.

2018-11-14 08:25 UTC, applejag requested changes

2018-11-14 08:25 UTC, applejag commented on KallesBank/Controllers/BankController.cs
> +            }
Valideringen går aldrig igenom. Din remote validation för bara med endast värdet av `AccountId1` eller `AccountId2`.

En rekommenderad lösning är att göra det via [`AdditionalFields`](https://docs.microsoft.com/en-us/dotnet/api/system.web.mvc.remoteattribute.additionalfields?view=aspnet-mvc-5.2#System_Web_Mvc_RemoteAttribute_AdditionalFields) på Remote attributet, likt så:
```cs
[Remote(controller: "Bank", action: "ValidateAccounts", AdditionalFields = nameof(AccountId2))]
```

Valideringen bör även kolla så att `AccountId1 != AccountId2`

2018-11-14 08:38 UTC, jilleJr commented on KallesBank/Controllers/BankController.cs
> +            }
Att valideringen kollas för båda element, på båda elementen, blir felaktigt extrasteg.

Är AccountId2 fältet tomt eller felaktig, så kommer denna implementation fortsätta klaga på AccountId1, även fast den är korrekt.

2018-11-20 21:57 UTC, Charbely commented on KallesBank/Controllers/BankController.cs
> +            }
Jag har nu åtgärdat detta. Ursäkta att det har dröjt.

2018-11-20 21:57 UTC, Charbely commented
Nu är allt åtgärdat

2018-11-20 22:45 UTC, applejag approved these changes
Najs najs!

Resolves #4

2018-11-20 22:46 UTC, merged